-- Full Schema Export for InfinityFree Deployment

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+05:30";

DROP TABLE IF EXISTS `admin_audit_logs`;
CREATE TABLE `admin_audit_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `action` varchar(50) NOT NULL,
  `target_table` varchar(50) DEFAULT NULL,
  `target_id` int DEFAULT NULL,
  `old_values` json DEFAULT NULL,
  `new_values` json DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_audit_admin` (`admin_id`),
  KEY `idx_audit_time` (`created_at`),
  KEY `idx_audit_target` (`target_table`,`target_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `admin_login_logs`;
CREATE TABLE `admin_login_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `admin_id` int DEFAULT NULL,
  `ip_address` varchar(45) NOT NULL,
  `user_agent` text,
  `status` enum('success','failed') NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_login_ip` (`ip_address`),
  KEY `idx_login_time` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `admins`;
CREATE TABLE `admins` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role_id` int NOT NULL,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `full_name` varchar(100) DEFAULT NULL,
  `status` enum('active','inactive','suspended') DEFAULT 'active',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_admin_status` (`status`),
  KEY `idx_admin_role` (`role_id`),
  CONSTRAINT `admins_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admins` (`id`, `role_id`, `username`, `email`, `password_hash`, `full_name`, `status`, `created_at`, `updated_at`, `deleted_at`, `deleted_by`) VALUES
('1', '1', 'admin', 'admin@aspord.com', '$argon2id$v=19$m=65536,t=4,p=1$alV2NWlUNDViai44Z1Zaeg$pAo1LNtE/m9Xa+30xzN3kGqK+aMw+dTJoyYCtTXViAU', 'System Administrator', 'active', '2026-02-09 12:39:40', '2026-02-09 12:51:45', NULL, NULL);

DROP TABLE IF EXISTS `menu_items`;
CREATE TABLE `menu_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `lang` varchar(5) NOT NULL,
  `category` varchar(50) NOT NULL,
  `name` varchar(255) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `img` varchar(255) DEFAULT '',
  `is_veg` tinyint(1) NOT NULL DEFAULT '1',
  `rating` decimal(2,1) DEFAULT NULL,
  `bestseller` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `lang_cat` (`lang`,`category`)
) ENGINE=InnoDB AUTO_INCREMENT=226 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `menu_items` (`id`, `lang`, `category`, `name`, `price`, `img`, `is_veg`, `rating`, `bestseller`) VALUES
('1', 'en', 'veg', 'Paneer Butter Masala', '210.00', 'panner_butter_masala.jpg', '1', NULL, '0'),
('2', 'en', 'veg', 'Kadai Paneer', '210.00', 'kadai_paneer.jpg', '1', NULL, '0'),
('3', 'en', 'veg', 'Shahi Paneer', '230.00', 'shahi_paneer.jpg', '1', NULL, '0'),
('4', 'en', 'veg', 'Veg Kolhapuri', '200.00', 'veg_kolhapuri.jpg', '1', NULL, '0'),
('5', 'en', 'veg', 'Mix Veg Curry', '180.00', 'Mix_Veg_Curry.jpg', '1', NULL, '0'),
('6', 'en', 'veg', 'Dal Tadka', '160.00', 'dal_tadka.jpg', '1', NULL, '0'),
('7', 'en', 'veg', 'Dal Fry', '150.00', 'dal_fry.jpg', '1', NULL, '0'),
('8', 'en', 'veg', 'Veg Handi', '190.00', 'veg_handi.jpg', '1', NULL, '0'),
('9', 'en', 'veg', 'Aloo Gobi', '140.00', 'aloo_gobi.jpg', '1', NULL, '0'),
('10', 'en', 'veg', 'Jeera Aloo', '130.00', 'jeera_aloo.jpg', '1', NULL, '0'),
('11', 'en', 'veg', 'Bhindi Masala', '150.00', 'bhindi_masala.jpg', '1', NULL, '0'),
('12', 'en', 'veg', 'Chole Masala', '160.00', 'chole_masala.jpg', '1', NULL, '0'),
('13', 'en', 'veg', 'Rajma Masala', '170.00', 'rajma.jpg', '1', NULL, '0'),
('14', 'en', 'veg', 'Malai Kofta', '240.00', 'malai_kofta.jpg', '1', NULL, '0'),
('15', 'en', 'veg', 'Veg Thali', '260.00', 'veg_thali.jpg', '1', NULL, '0'),
('16', 'en', 'nonveg', 'Chicken Butter Masala', '280.00', 'Chicken_Butter_Masala.jpg', '0', NULL, '0'),
('17', 'en', 'nonveg', 'Chicken Tikka Masala', '270.00', 'Chicken_Tikka_Masala.webp', '0', NULL, '0'),
('18', 'en', 'nonveg', 'Chicken Kolhapuri', '260.00', 'Chicken_Kolhapuri.jpg', '0', NULL, '0'),
('19', 'en', 'nonveg', 'Chicken Handi', '290.00', 'Chicken_Handi.webp', '0', NULL, '0'),
('20', 'en', 'nonveg', 'Chicken Curry', '240.00', 'Chicken_Curry.webp', '0', NULL, '0'),
('21', 'en', 'nonveg', 'Chicken Biryani', '300.00', 'Chicken_Biryani.webp', '0', NULL, '0'),
('22', 'en', 'nonveg', 'Mutton Biryani', '380.00', 'Mutton_Biryani.webp', '0', NULL, '0'),
('23', 'en', 'nonveg', 'Mutton Curry', '360.00', 'Mutton_curry.webp', '0', NULL, '0'),
('24', 'en', 'nonveg', 'Egg Curry', '190.00', 'Egg_Curry.webp', '0', NULL, '0'),
('25', 'en', 'nonveg', 'Egg Masala', '180.00', 'Egg_Masala.webp', '0', NULL, '0'),
('26', 'en', 'nonveg', 'Fish Curry', '320.00', 'Fish_Curry.jpg', '0', NULL, '0'),
('27', 'en', 'nonveg', 'Fish Fry', '340.00', 'Fish_Fry.webp', '0', NULL, '0'),
('28', 'en', 'nonveg', 'Chicken Lollipop', '260.00', 'Chicken_Lollipop.webp', '0', NULL, '0'),
('29', 'en', 'nonveg', 'Tandoori Chicken', '350.00', 'Tandoori_Chicken.webp', '0', NULL, '0'),
('30', 'en', 'nonveg', 'Chicken Thali', '330.00', 'Chicken_Thali.webp', '0', NULL, '0'),
('31', 'en', 'chinese', 'Veg Hakka Noodles', '160.00', 'Veg-Hakka-Noodles.jpg', '1', NULL, '0'),
('32', 'en', 'chinese', 'Veg Fried Rice', '150.00', 'Veg-Fried-Rice.webp', '1', NULL, '0'),
('33', 'en', 'chinese', 'Veg Manchurian', '170.00', 'Veg-Manchurian.jpg', '1', NULL, '0'),
('34', 'en', 'chinese', 'Paneer Chilli', '200.00', 'Panner-Chilli.webp', '1', NULL, '0'),
('35', 'en', 'chinese', 'Veg Spring Roll', '140.00', 'Veg-Spring-Roll.webp', '1', NULL, '0'),
('36', 'en', 'chinese', 'Chicken Fried Rice', '190.00', 'Chicken-Fried-Rice.jpg', '0', NULL, '0'),
('37', 'en', 'chinese', 'Chicken Noodles', '200.00', 'Chicken-Noodles.jpg', '0', NULL, '0'),
('38', 'en', 'chinese', 'Chicken Manchurian', '210.00', 'Chicken-Manchurian.jpg', '0', NULL, '0'),
('39', 'en', 'chinese', 'Chicken Chilli', '230.00', 'Chicken-Chilli.jpg', '0', NULL, '0'),
('40', 'en', 'chinese', 'Schezwan Noodles', '180.00', 'Schezwan-Noodles.webp', '1', NULL, '0'),
('41', 'en', 'chinese', 'Schezwan Rice', '170.00', 'Schezwan-Rice.jpg', '1', NULL, '0'),
('42', 'en', 'chinese', 'Triple Fried Rice', '220.00', 'Triple-Fried-Rice.jpg', '1', NULL, '0'),
('43', 'en', 'chinese', 'Honey Chilli Potato', '160.00', 'Honey-Chilli-Potato.jpg', '1', NULL, '0'),
('45', 'en', 'chinese', 'Chinese Bhel', '130.00', 'Chinese-Bhel.jpg', '1', NULL, '0'),
('46', 'en', 'south', 'Plain Dosa', '120.00', 'masala_dosa.jpg', '1', NULL, '0'),
('47', 'en', 'south', 'Masala Dosa', '150.00', 'masala_dosa.jpg', '1', NULL, '0'),
('48', 'en', 'south', 'Mysore Dosa', '170.00', 'mysore_masala_dosa.webp', '1', NULL, '0'),
('49', 'en', 'south', 'Idli Sambar', '100.00', 'idli_sambar.jpg', '1', NULL, '0'),
('50', 'en', 'south', 'Medu Vada', '110.00', 'medu_wada.jpg', '1', NULL, '0'),
('51', 'en', 'south', 'Uttapam', '140.00', 'uttapam.jpg', '1', NULL, '0'),
('52', 'en', 'south', 'Rava Dosa', '160.00', 'RAVA_DOSA.jpg', '1', NULL, '0'),
('53', 'en', 'south', 'Set Dosa', '150.00', 'set_dosa.jpg', '1', NULL, '0'),
('54', 'en', 'south', 'Sambar Rice', '140.00', 'sambar_rice.png', '1', NULL, '0'),
('55', 'en', 'south', 'Curd Rice', '120.00', 'curd_rice.jpg', '1', NULL, '0'),
('56', 'en', 'south', 'Lemon Rice', '130.00', 'Lemon_rice.jpg', '1', NULL, '0'),
('57', 'en', 'south', 'Rasam Rice', '120.00', 'Rasam_rice.jpg', '1', NULL, '0'),
('58', 'en', 'south', 'South Indian Thali', '260.00', 'South_indian_thali.jpg', '1', NULL, '0'),
('59', 'en', 'south', 'Pongal', '140.00', 'pongal.jpg', '1', NULL, '0'),
('60', 'en', 'south', 'Filter Coffee', '60.00', 'Filter_coffee.jpg', '1', NULL, '0'),
('61', 'en', 'snacks', 'Samosa', '30.00', 'Samosa.jpg', '1', NULL, '0'),
('62', 'en', 'snacks', 'Kachori', '35.00', 'Kachori.jpg', '1', NULL, '0'),
('63', 'en', 'snacks', 'Vada Pav', '25.00', 'vada_pav.jpg', '1', NULL, '0'),
('64', 'en', 'snacks', 'Pav Bhaji', '150.00', 'Pav_bhaji.jpg', '1', NULL, '0'),
('65', 'en', 'snacks', 'Misal Pav', '140.00', 'misal_pav.jpg', '1', NULL, '0'),
('66', 'en', 'snacks', 'Bhel Puri', '80.00', 'Bhel_puri.jpg', '1', NULL, '0'),
('67', 'en', 'snacks', 'Sev Puri', '90.00', 'sev_puri.jpg', '1', NULL, '0'),
('68', 'en', 'snacks', 'Dahi Puri', '100.00', 'dahi_puri.jpg', '1', NULL, '0'),
('69', 'en', 'snacks', 'Cheese Sandwich', '120.00', 'Cheese_sandwich.jpg', '1', NULL, '0'),
('70', 'en', 'snacks', 'Grilled Sandwich', '130.00', 'Grilled_sandwich.jpg', '1', NULL, '0'),
('71', 'en', 'snacks', 'French Fries', '110.00', 'French_fries.jpg', '1', NULL, '0'),
('72', 'en', 'snacks', 'Cheese Fries', '140.00', 'Cheese_fries.jpg', '1', NULL, '0'),
('73', 'en', 'snacks', 'Veg Puff', '35.00', 'veg_puff.jpg', '1', NULL, '0'),
('74', 'en', 'snacks', 'Tea', '20.00', 'tea.jpg', '1', NULL, '0'),
('75', 'en', 'snacks', 'Cold Coffee', '90.00', 'cold_coffee.jpg', '1', NULL, '0'),
('76', 'hi', 'veg', 'पनीर बटर मसाला', '220.00', 'panner_butter_masala.jpg', '1', NULL, '0'),
('77', 'hi', 'veg', 'कड़ाई पनीर', '210.00', 'kadai_paneer.jpg', '1', NULL, '0'),
('78', 'hi', 'veg', 'शाही पनीर', '230.00', 'shahi_paneer.jpg', '1', NULL, '0'),
('79', 'hi', 'veg', 'वेज कोल्हापुरी', '200.00', 'veg_kolhapuri.jpg', '1', NULL, '0'),
('80', 'hi', 'veg', 'मिक्स वेज करी', '180.00', 'Mix_Veg_Curry.jpg', '1', NULL, '0'),
('81', 'hi', 'veg', 'दाल तड़का', '160.00', 'dal_tadka.jpg', '1', NULL, '0'),
('82', 'hi', 'veg', 'दाल फ्राय', '150.00', 'dal_fry.jpg', '1', NULL, '0'),
('83', 'hi', 'veg', 'वेज हांडी', '190.00', 'veg_handi.jpg', '1', NULL, '0'),
('84', 'hi', 'veg', 'आलू गोभी', '140.00', 'aloo_gobi.jpg', '1', NULL, '0'),
('85', 'hi', 'veg', 'जीरा आलू', '130.00', 'jeera_aloo.jpg', '1', NULL, '0'),
('86', 'hi', 'veg', 'भिंडी मसाला', '150.00', 'bhindi_masala.jpg', '1', NULL, '0'),
('87', 'hi', 'veg', 'छोले मसाला', '160.00', 'chole_masala.jpg', '1', NULL, '0'),
('88', 'hi', 'veg', 'राजमा मसाला', '170.00', 'rajma.jpg', '1', NULL, '0'),
('89', 'hi', 'veg', 'मलाई कोफ्ता', '240.00', 'malai_kofta.jpg', '1', NULL, '0'),
('90', 'hi', 'veg', 'वेज थाली', '260.00', 'veg_thali.jpg', '1', NULL, '0'),
('91', 'hi', 'nonveg', 'चिकन बटर मसाला', '280.00', 'Chicken_Butter_Masala.jpg', '0', NULL, '0'),
('92', 'hi', 'nonveg', 'चिकन टिक्का मसाला', '270.00', 'Chicken_Tikka_Masala.webp', '0', NULL, '0'),
('93', 'hi', 'nonveg', 'चिकन कोल्हापुरी', '260.00', 'Chicken_Kolhapuri.jpg', '0', NULL, '0'),
('94', 'hi', 'nonveg', 'चिकन हांडी', '290.00', 'Chicken_Handi.webp', '0', NULL, '0'),
('95', 'hi', 'nonveg', 'चिकन करी', '240.00', 'Chicken_Curry.webp', '0', NULL, '0'),
('96', 'hi', 'nonveg', 'चिकन बिरयानी', '300.00', 'Chicken_Biryani.webp', '0', NULL, '0'),
('97', 'hi', 'nonveg', 'मटन बिरयानी', '380.00', 'Mutton_Biryani.webp', '0', NULL, '0'),
('98', 'hi', 'nonveg', 'मटन करी', '360.00', 'Mutton_curry.webp', '0', NULL, '0'),
('99', 'hi', 'nonveg', 'अंडा करी', '190.00', 'Egg_Curry.webp', '0', NULL, '0'),
('100', 'hi', 'nonveg', 'अंडा मसाला', '180.00', 'Egg_Masala.webp', '0', NULL, '0'),
('101', 'hi', 'nonveg', 'फिश करी', '320.00', 'Fish_Curry.jpg', '0', NULL, '0'),
('102', 'hi', 'nonveg', 'फिश फ्राय', '340.00', 'Fish_Fry.webp', '0', NULL, '0'),
('103', 'hi', 'nonveg', 'चिकन लॉलीपॉप', '260.00', 'Chicken_Lollipop.webp', '0', NULL, '0'),
('104', 'hi', 'nonveg', 'तंदूरी चिकन', '350.00', 'Tandoori_Chicken.webp', '0', NULL, '0'),
('105', 'hi', 'nonveg', 'चिकन थाली', '330.00', 'Chicken_Thali.webp', '0', NULL, '0'),
('106', 'hi', 'chinese', 'वेज हक्का नूडल्स', '160.00', 'Veg-Hakka-Noodles.jpg', '1', NULL, '0'),
('107', 'hi', 'chinese', 'वेज फ्राइड राइस', '150.00', 'Veg-Fried-Rice.webp', '1', NULL, '0'),
('108', 'hi', 'chinese', 'वेज मंचूरियन', '170.00', 'Veg-Manchurian.jpg', '1', NULL, '0'),
('109', 'hi', 'chinese', 'पनीर चिली', '200.00', 'Panner-Chilli.webp', '1', NULL, '0'),
('110', 'hi', 'chinese', 'वेज स्प्रिंग रोल', '140.00', 'Veg-Spring-Roll.webp', '1', NULL, '0'),
('111', 'hi', 'chinese', 'चिकन फ्राइड राइस', '190.00', 'Chicken-Fried-Rice.jpg', '0', NULL, '0'),
('112', 'hi', 'chinese', 'चिकन नूडल्स', '200.00', 'Chicken-Noodles.jpg', '0', NULL, '0'),
('113', 'hi', 'chinese', 'चिकन मंचूरियन', '210.00', 'Chicken-Manchurian.jpg', '0', NULL, '0'),
('114', 'hi', 'chinese', 'चिकन चिली', '230.00', 'Chicken-Chilli.jpg', '0', NULL, '0'),
('115', 'hi', 'chinese', 'शेजवान नूडल्स', '180.00', 'Schezwan-Noodles.webp', '1', NULL, '0'),
('116', 'hi', 'chinese', 'शेजवान राइस', '170.00', 'Schezwan-Rice.jpg', '1', NULL, '0'),
('117', 'hi', 'chinese', 'ट्रिपल फ्राइड राइस', '220.00', 'Triple-Fried-Rice.jpg', '1', NULL, '0'),
('118', 'hi', 'chinese', 'हनी चिली पोटैटो', '160.00', 'Honey-Chilli-Potato.jpg', '1', NULL, '0'),
('119', 'hi', 'chinese', 'अमेरिकन चॉप्सुए', '210.00', 'American-Chopsuey.jpg', '1', NULL, '0'),
('120', 'hi', 'chinese', 'चाइनीज भेल', '130.00', 'Chinese-Bhel.jpg', '1', NULL, '0'),
('121', 'hi', 'south', 'प्लेन डोसा', '120.00', 'masala_dosa.jpg', '1', NULL, '0'),
('122', 'hi', 'south', 'मसाला डोसा', '150.00', 'masala_dosa.jpg', '1', NULL, '0'),
('123', 'hi', 'south', 'मैसूर डोसा', '170.00', 'mysore_masala_dosa.webp', '1', NULL, '0'),
('124', 'hi', 'south', 'इडली सांभर', '100.00', 'idli_sambar.jpg', '1', NULL, '0'),
('125', 'hi', 'south', 'मेदु वडा', '110.00', 'medu_wada.jpg', '1', NULL, '0'),
('126', 'hi', 'south', 'उत्तपम', '140.00', 'uttapam.jpg', '1', NULL, '0'),
('127', 'hi', 'south', 'रवा डोसा', '160.00', 'RAVA_DOSA.jpg', '1', NULL, '0'),
('128', 'hi', 'south', 'सेट डोसा', '150.00', 'set_dosa.jpg', '1', NULL, '0'),
('129', 'hi', 'south', 'सांभर राइस', '140.00', 'sambar_rice.png', '1', NULL, '0'),
('130', 'hi', 'south', 'दही चावल', '120.00', 'curd_rice.jpg', '1', NULL, '0'),
('131', 'hi', 'south', 'नींबू चावल', '130.00', 'Lemon_rice.jpg', '1', NULL, '0'),
('132', 'hi', 'south', 'रसम चावल', '120.00', 'Rasam_rice.jpg', '1', NULL, '0'),
('133', 'hi', 'south', 'साउथ इंडियन थाली', '260.00', 'South_indian_thali.jpg', '1', NULL, '0'),
('134', 'hi', 'south', 'पोंगल', '140.00', 'pongal.jpg', '1', NULL, '0'),
('135', 'hi', 'south', 'फिल्टर कॉफी', '60.00', 'Filter_coffee.jpg', '1', NULL, '0'),
('136', 'hi', 'snacks', 'समोसा', '30.00', 'Samosa.jpg', '1', NULL, '0'),
('137', 'hi', 'snacks', 'कचौरी', '35.00', 'Kachori.jpg', '1', NULL, '0'),
('138', 'hi', 'snacks', 'वड़ा पाव', '25.00', 'vada_pav.jpg', '1', NULL, '0'),
('139', 'hi', 'snacks', 'पाव भाजी', '150.00', 'Pav_bhaji.jpg', '1', NULL, '0'),
('140', 'hi', 'snacks', 'मिसल पाव', '140.00', 'misal_pav.jpg', '1', NULL, '0'),
('141', 'hi', 'snacks', 'भेल पूरी', '80.00', 'Bhel_puri.jpg', '1', NULL, '0'),
('142', 'hi', 'snacks', 'सेव पूरी', '90.00', 'sev_puri.jpg', '1', NULL, '0'),
('143', 'hi', 'snacks', 'दही पूरी', '100.00', 'dahi_puri.jpg', '1', NULL, '0'),
('144', 'hi', 'snacks', 'चीज़ सैंडविच', '120.00', 'Cheese_sandwich.jpg', '1', NULL, '0'),
('145', 'hi', 'snacks', 'ग्रिल्ड सैंडविच', '130.00', 'Grilled_sandwich.jpg', '1', NULL, '0'),
('146', 'hi', 'snacks', 'फ्रेंच फ्राइज', '110.00', 'French_fries.jpg', '1', NULL, '0'),
('147', 'hi', 'snacks', 'चीज़ फ्राइज', '140.00', 'Cheese_fries.jpg', '1', NULL, '0'),
('148', 'hi', 'snacks', 'वेज पफ', '35.00', 'veg_puff.jpg', '1', NULL, '0'),
('149', 'hi', 'snacks', 'चाय', '20.00', 'tea.jpg', '1', NULL, '0'),
('150', 'hi', 'snacks', 'कोल्ड कॉफी', '90.00', 'cold_coffee.jpg', '1', NULL, '0'),
('151', 'mr', 'veg', 'पनीर बटर मसाला', '220.00', 'panner_butter_masala.jpg', '1', NULL, '0'),
('152', 'mr', 'veg', 'कढई पनीर', '210.00', 'kadai_paneer.jpg', '1', NULL, '0'),
('153', 'mr', 'veg', 'शाही पनीर', '230.00', 'shahi_paneer.jpg', '1', NULL, '0'),
('154', 'mr', 'veg', 'वेज कोल्हापुरी', '200.00', 'veg_kolhapuri.jpg', '1', NULL, '0'),
('155', 'mr', 'veg', 'मिक्स वेज भाजी', '180.00', 'Mix_Veg_Curry.jpg', '1', NULL, '0'),
('156', 'mr', 'veg', 'डाळ तडका', '160.00', 'dal_tadka.jpg', '1', NULL, '0'),
('157', 'mr', 'veg', 'डाळ फ्राय', '150.00', 'dal_fry.jpg', '1', NULL, '0'),
('158', 'mr', 'veg', 'वेज हांडी', '190.00', 'veg_handi.jpg', '1', NULL, '0'),
('159', 'mr', 'veg', 'आलू गोबी', '140.00', 'aloo_gobi.jpg', '1', NULL, '0'),
('160', 'mr', 'veg', 'जिरा आलू', '130.00', 'jeera_aloo.jpg', '1', NULL, '0'),
('161', 'mr', 'veg', 'भेंडी मसाला', '150.00', 'bhindi_masala.jpg', '1', NULL, '0'),
('162', 'mr', 'veg', 'छोले मसाला', '160.00', 'chole_masala.jpg', '1', NULL, '0'),
('163', 'mr', 'veg', 'राजमा मसाला', '170.00', 'rajma.jpg', '1', NULL, '0'),
('164', 'mr', 'veg', 'मलाई कोफ्ता', '240.00', 'malai_kofta.jpg', '1', NULL, '0'),
('165', 'mr', 'veg', 'वेज थाळी', '260.00', 'veg_thali.jpg', '1', NULL, '0'),
('166', 'mr', 'nonveg', 'चिकन बटर मसाला', '280.00', 'Chicken_Butter_Masala.jpg', '0', NULL, '0'),
('167', 'mr', 'nonveg', 'चिकन टिक्का मसाला', '270.00', 'Chicken_Tikka_Masala.webp', '0', NULL, '0'),
('168', 'mr', 'nonveg', 'चिकन कोल्हापुरी', '260.00', 'Chicken_Kolhapuri.jpg', '0', NULL, '0'),
('169', 'mr', 'nonveg', 'चिकन हांडी', '290.00', 'Chicken_Handi.webp', '0', NULL, '0'),
('170', 'mr', 'nonveg', 'चिकन रस्सा', '240.00', 'Chicken_Curry.webp', '0', NULL, '0'),
('171', 'mr', 'nonveg', 'चिकन बिर्याणी', '300.00', 'Chicken_Biryani.webp', '0', NULL, '0'),
('172', 'mr', 'nonveg', 'मटण बिर्याणी', '380.00', 'Mutton_Biryani.webp', '0', NULL, '0'),
('173', 'mr', 'nonveg', 'मटण रस्सा', '360.00', 'Mutton_curry.webp', '0', NULL, '0'),
('174', 'mr', 'nonveg', 'अंडा करी', '190.00', 'Egg_Curry.webp', '0', NULL, '0'),
('175', 'mr', 'nonveg', 'अंडा मसाला', '180.00', 'Egg_Masala.webp', '0', NULL, '0'),
('176', 'mr', 'nonveg', 'फिश करी', '320.00', 'Fish_Curry.jpg', '0', NULL, '0'),
('177', 'mr', 'nonveg', 'फिश फ्राय', '340.00', 'Fish_Fry.webp', '0', NULL, '0'),
('178', 'mr', 'nonveg', 'चिकन लॉलीपॉप', '260.00', 'Chicken_Lollipop.webp', '0', NULL, '0'),
('179', 'mr', 'nonveg', 'तंदूरी चिकन', '350.00', 'Tandoori_Chicken.webp', '0', NULL, '0'),
('180', 'mr', 'nonveg', 'चिकन थाळी', '330.00', 'Chicken_Thali.webp', '0', NULL, '0'),
('181', 'mr', 'chinese', 'वेज हक्का नूडल्स', '160.00', 'Veg-Hakka-Noodles.jpg', '1', NULL, '0'),
('182', 'mr', 'chinese', 'वेज फ्राइड राईस', '150.00', 'Veg-Fried-Rice.webp', '1', NULL, '0'),
('183', 'mr', 'chinese', 'वेज मंचुरियन', '170.00', 'Veg-Manchurian.jpg', '1', NULL, '0'),
('184', 'mr', 'chinese', 'पनीर चिली', '200.00', 'Panner-Chilli.webp', '1', NULL, '0'),
('185', 'mr', 'chinese', 'वेज स्प्रिंग रोल', '140.00', 'Veg-Spring-Roll.webp', '1', NULL, '0'),
('186', 'mr', 'chinese', 'चिकन फ्राइड राईस', '190.00', 'Chicken-Fried-Rice.jpg', '0', NULL, '0'),
('187', 'mr', 'chinese', 'चिकन नूडल्स', '200.00', 'Chicken-Noodles.jpg', '0', NULL, '0'),
('188', 'mr', 'chinese', 'चिकन मंचुरियन', '210.00', 'Chicken-Manchurian.jpg', '0', NULL, '0'),
('189', 'mr', 'chinese', 'चिकन चिली', '230.00', 'Chicken-Chilli.jpg', '0', NULL, '0'),
('190', 'mr', 'chinese', 'शेजवान नूडल्स', '180.00', 'Schezwan-Noodles.webp', '1', NULL, '0'),
('191', 'mr', 'chinese', 'शेजवान राईस', '170.00', 'Schezwan-Rice.jpg', '1', NULL, '0'),
('192', 'mr', 'chinese', 'ट्रिपल फ्राइड राईस', '220.00', 'Triple-Fried-Rice.jpg', '1', NULL, '0'),
('193', 'mr', 'chinese', 'हनी चिली पोटॅटो', '160.00', 'Honey-Chilli-Potato.jpg', '1', NULL, '0'),
('194', 'mr', 'chinese', 'अमेरिकन चॉप्सुए', '210.00', 'American-Chopsuey.jpg', '1', NULL, '0'),
('195', 'mr', 'chinese', 'चायनीज भेल', '130.00', 'Chinese-Bhel.jpg', '1', NULL, '0'),
('196', 'mr', 'south', 'साधा डोसा', '120.00', 'masala_dosa.jpg', '1', NULL, '0'),
('197', 'mr', 'south', 'मसाला डोसा', '150.00', 'masala_dosa.jpg', '1', NULL, '0'),
('198', 'mr', 'south', 'मैसूर डोसा', '170.00', 'mysore_masala_dosa.webp', '1', NULL, '0'),
('199', 'mr', 'south', 'इडली सांबार', '100.00', 'idli_sambar.jpg', '1', NULL, '0'),
('200', 'mr', 'south', 'मेदू वडा', '110.00', 'medu_wada.jpg', '1', NULL, '0'),
('201', 'mr', 'south', 'उत्तपम', '140.00', 'uttapam.jpg', '1', NULL, '0'),
('202', 'mr', 'south', 'रवा डोसा', '160.00', 'RAVA_DOSA.jpg', '1', NULL, '0'),
('203', 'mr', 'south', 'सेट डोसा', '150.00', 'set_dosa.jpg', '1', NULL, '0'),
('204', 'mr', 'south', 'सांबार राईस', '140.00', 'sambar_rice.png', '1', NULL, '0'),
('205', 'mr', 'south', 'दही भात', '120.00', 'curd_rice.jpg', '1', NULL, '0'),
('206', 'mr', 'south', 'लिंबू भात', '130.00', 'Lemon_rice.jpg', '1', NULL, '0'),
('207', 'mr', 'south', 'रसम भात', '120.00', 'Rasam_rice.jpg', '1', NULL, '0'),
('208', 'mr', 'south', 'साउथ इंडियन थाळी', '260.00', 'South_indian_thali.jpg', '1', NULL, '0'),
('209', 'mr', 'south', 'पोंगल', '140.00', 'pongal.jpg', '1', NULL, '0'),
('210', 'mr', 'south', 'फिल्टर कॉफी', '60.00', 'Filter_coffee.jpg', '1', NULL, '0'),
('211', 'mr', 'snacks', 'समोसा', '30.00', 'Samosa.jpg', '1', NULL, '0'),
('212', 'mr', 'snacks', 'कचोरी', '35.00', 'Kachori.jpg', '1', NULL, '0'),
('213', 'mr', 'snacks', 'वडापाव', '25.00', 'vada_pav.jpg', '1', NULL, '0'),
('214', 'mr', 'snacks', 'पाव भाजी', '150.00', 'Pav_bhaji.jpg', '1', NULL, '0'),
('215', 'mr', 'snacks', 'मिसळ पाव', '140.00', 'misal_pav.jpg', '1', NULL, '0'),
('216', 'mr', 'snacks', 'भेळपुरी', '80.00', 'Bhel_puri.jpg', '1', NULL, '0'),
('217', 'mr', 'snacks', 'सेवपुरी', '90.00', 'sev_puri.jpg', '1', NULL, '0'),
('218', 'mr', 'snacks', 'दहीपुरी', '100.00', 'dahi_puri.jpg', '1', NULL, '0'),
('219', 'mr', 'snacks', 'चीज सँडविच', '120.00', 'Cheese_sandwich.jpg', '1', NULL, '0'),
('220', 'mr', 'snacks', 'ग्रिल्ड सँडविच', '130.00', 'Grilled_sandwich.jpg', '1', NULL, '0'),
('221', 'mr', 'snacks', 'फ्रेंच फ्राइज', '110.00', 'French_fries.jpg', '1', NULL, '0'),
('222', 'mr', 'snacks', 'चीज फ्राइज', '140.00', 'Cheese_fries.jpg', '1', NULL, '0'),
('223', 'mr', 'snacks', 'वेज पफ', '35.00', 'veg_puff.jpg', '1', NULL, '0'),
('224', 'mr', 'snacks', 'चहा', '20.00', 'tea.jpg', '1', NULL, '0'),
('225', 'mr', 'snacks', 'कोल्ड कॉफी', '90.00', 'cold_coffee.jpg', '1', NULL, '0');

DROP TABLE IF EXISTS `order_items`;
CREATE TABLE `order_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `item_id` int NOT NULL,
  `quantity` int NOT NULL,
  `unit_price` decimal(10,2) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_oi_order` (`order_id`),
  KEY `idx_oi_item` (`item_id`),
  KEY `idx_oi_date` (`created_at`),
  CONSTRAINT `order_items_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` varchar(50) NOT NULL,
  `user_id` int NOT NULL,
  `table_id` int DEFAULT NULL,
  `session_id` int DEFAULT NULL,
  `cart_data` longtext NOT NULL,
  `total_amount` decimal(10,2) NOT NULL,
  `status` enum('pending','confirmed','completed','cancelled') NOT NULL DEFAULT 'pending',
  `payment_status` enum('pending','paid','failed') NOT NULL DEFAULT 'pending',
  `payment_method` enum('online','cash') DEFAULT 'online',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_id` (`order_id`),
  KEY `user_id` (`user_id`),
  KEY `fk_orders_session` (`session_id`),
  CONSTRAINT `fk_orders_session` FOREIGN KEY (`session_id`) REFERENCES `table_sessions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `orders_chk_1` CHECK (json_valid(`cart_data`))
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `otp_requests`;
CREATE TABLE `otp_requests` (
  `id` int NOT NULL AUTO_INCREMENT,
  `mobile` varchar(15) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `otp` varchar(10) NOT NULL,
  `expires_at` timestamp NOT NULL,
  `is_verified` tinyint(1) NOT NULL DEFAULT '0',
  `attempts` int NOT NULL DEFAULT '0',
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `mobile` (`mobile`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `slug` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `role_permissions`;
CREATE TABLE `role_permissions` (
  `role_id` int NOT NULL,
  `permission_id` int NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `permission_id` (`permission_id`),
  CONSTRAINT `role_permissions_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `role_permissions_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `slug` varchar(50) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `table_sessions`;
CREATE TABLE `table_sessions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `table_id` int NOT NULL,
  `order_id` int DEFAULT NULL,
  `started_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ended_at` timestamp NULL DEFAULT NULL,
  `total_amount` decimal(10,2) DEFAULT '0.00',
  `payment_method` enum('online','cash','pending') DEFAULT 'pending',
  `status` enum('active','completed','cancelled') DEFAULT 'active',
  PRIMARY KEY (`id`),
  KEY `table_id` (`table_id`),
  KEY `order_id` (`order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `tables`;
CREATE TABLE `tables` (
  `id` int NOT NULL AUTO_INCREMENT,
  `table_number` varchar(20) NOT NULL,
  `table_name` varchar(100) DEFAULT NULL,
  `capacity` int DEFAULT '4',
  `qr_code_path` varchar(255) DEFAULT NULL,
  `payment_status` enum('vacant','pending','done','partial') DEFAULT 'vacant',
  `current_order_id` int DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `table_number` (`table_number`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `tables` (`id`, `table_number`, `table_name`, `capacity`, `qr_code_path`, `payment_status`, `current_order_id`, `created_at`, `updated_at`) VALUES
('1', 'TABLE1', 'Window Table 1', '2', 'qr_codes/table_1_1770730745.png', 'vacant', NULL, '2026-02-09 21:06:41', '2026-02-11 12:51:26'),
('2', 'TABLE2', 'Window Table 2', '2', NULL, 'vacant', NULL, '2026-02-09 21:06:41', '2026-02-10 23:08:52'),
('3', 'TABLE3', 'Corner Table', '4', NULL, 'vacant', NULL, '2026-02-09 21:06:41', '2026-02-10 23:08:52'),
('4', 'TABLE4', 'Center Table 1', '4', NULL, 'vacant', NULL, '2026-02-09 21:06:41', '2026-02-10 23:08:52'),
('5', 'TABLE5', 'Center Table 2', '4', NULL, 'vacant', NULL, '2026-02-09 21:06:41', '2026-02-10 23:08:52'),
('6', 'TABLE6', 'Center Table 3', '6', NULL, 'vacant', NULL, '2026-02-09 21:06:41', '2026-02-10 23:08:52'),
('7', 'TABLE7', 'VIP Table', '8', NULL, 'vacant', NULL, '2026-02-09 21:06:41', '2026-02-10 23:08:52'),
('8', 'TABLE8', 'Outdoor Table 1', '4', NULL, 'vacant', NULL, '2026-02-09 21:06:41', '2026-02-10 23:08:52'),
('9', 'TABLE9', 'Outdoor Table 2', '4', NULL, 'vacant', NULL, '2026-02-09 21:06:41', '2026-02-10 23:08:52'),
('10', 'TABLE10', 'Bar Counter', '3', NULL, 'vacant', NULL, '2026-02-09 21:06:41', '2026-02-10 23:08:52');

DROP TABLE IF EXISTS `user_sessions`;
CREATE TABLE `user_sessions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `session_id` varchar(255) NOT NULL,
  `user_id` int NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `mobile` varchar(15) DEFAULT NULL,
  `expires_at` timestamp NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `session_id` (`session_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `user_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `mobile` varchar(15) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mobile` (`mobile`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

COMMIT;
